### ISSUE TITLE
No margin between votes

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-apps#665] opened 2019-02-12 14:24 UTC
![image](https://user-images.githubusercontent.com/718208/52641848-11ecf180-2eda-11e9-82a9-c7d5f0ad231d.png)

Using latest Chromium on Linux.

**Comment by sohkai** [comment] 2019-02-12 16:21
:/ this looks like a rendering issue for `grid` on specific versions of chrome.

Chrome Version 72.0.3626.96 (Official Build) (64-bit) on macOS does not have this issue.

cc @bpierre @AquiGorka I don't think there's a grid property that tells it to shrink, but that's what it looked like it was doing before on a slightly outdated version (1 week old).

**Comment by AquiGorka** [comment] 2019-02-13 07:55
Will look into this. @jounih had encountered the behavior before but we dismissed it as it was not part of the `responsive` updates and I was not able to reproduce.
Thanks for letting me know.

**Comment by sohkai** [comment] 2019-04-14 09:33
@luisivan I believe this is now fixed in newer versions of Chrome.

**Closed by sohkai** 2019-04-14 09:33 UTC
Labels: app: voting, bug, component: frontend
