### ISSUE TITLE
Token Manager: "Burn token" action in Permissions is inconsistent with "Remove token" button in Token Manager

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#509] opened 2018-10-19 12:46 UTC
In the Permissions app the action is called "Burn tokens" but in the Token Manager app it is called "Remove tokens". They should be called the same thing so users are not confused.

![aragon_burn_remove](https://user-images.githubusercontent.com/9424721/47218966-c0aa7680-d3ad-11e8-96f1-065e8bc7239d.png)

![aragon_burn_revoke](https://user-images.githubusercontent.com/9424721/47218975-c43dfd80-d3ad-11e8-902b-e444e6f50581.png)

**Comment by IvanTheGreatDev** [comment] 2018-10-20 20:11
Hmm, well the first one says `assign` (which sounds like it doesn't involve minting) and `remove` while the second one says `mint`, `assign` and `burn`.

Are remove and burn different? What's the difference between assign and mint?

**Comment by sohkai** [comment] 2018-10-21 09:11
@IvanTheGreatDev These terms are indeed a bit confusing.

The terminology we use in the contracts:

- "mint": mint tokens to a receiver
- "issue": mint tokens to the token manager itself (to be later "assigned")
- "assign": assign tokens from the token manager to a receiver
- "burn": destroy tokens from an account holder

In the frontend, these terms have been mapped to:

- "assign tokens" -> "mint"
- "remove tokens" -> "burn"

---------------------

We should align both labels to their corresponding actions.

**Comment by IvanTheGreatDev** [comment] 2018-10-21 09:28
Okay so I will prepare the front-end to rename assign to mint and remove to burn if they appear to be used in the wrong context.

**Comment by IvanTheGreatDev** [comment] 2018-10-21 09:59
Hmm, is there any guide to using and setting up the apps? I've tried to open up the token-manager app and I'm stuck at the `assign tokens` front page. I enter an address and amount but then when I click assign the address window closes and nothing happens.

**Comment by john-light** [comment] 2018-10-21 10:42
FWIW I did not intend with this issue to introduce technical terms like "mint" and "burn" to the frontend, rather I'm hoping that we can abstract those technical terms away from users everywhere. Are the "action" strings in the Permissions app coming directly from the contracts or some middle-layer?

**Comment by sohkai** [comment] 2018-10-23 11:41
They are provided by an app developer as part of the `arapp.json`. The role ID should match the one they use in the contract, but the description can be anything.

I agree, "burn" specifically is quite unfriendly. To compound this problem, the radspec string we have for `burnTokens()` is "Burn X tokens from Y" so users will also see this on the signing panel.

**Comment by IvanTheGreatDev** [comment] 2018-11-03 11:19
Gotcha, am away until the 10th, if theres anyone who wants to take this before I'm back feel free to do so.

**Comment by bpierre** [comment] 2019-03-21 13:26
@aragon/design

In the Token Manager app, we are using the terms “Assign” / “Remove” in several places:

<img width="1056" alt="screen-1" src="https://user-images.githubusercontent.com/36158/54753545-94f01e80-4be1-11e9-891d-faa55ebb8373.png">

<img width="1055" alt="screen-2" src="https://user-images.githubusercontent.com/36158/54753546-94f01e80-4be1-11e9-9af6-af26c8d18bf3.png">

<img width="1056" alt="screen-3" src="https://user-images.githubusercontent.com/36158/54753547-96b9e200-4be1-11e9-81a0-c3799d9485a4.png">

We could change these terms to be closer to the terms used in the permissions, but the problem is that the UI doesn’t exactly match the permissions provided by the app:

- The UI uses the term “Assign” to call an action that requires the **Mint tokens** permission. The **Issue tokens** and **Assign tokens** permissions are not used from the UI.
- The UI uses the term “Remove” to call an action that requires the **Burn tokens** permission.

I see two solutions in the short term:

- **1/** Rename “Assign” in the UI to something different from the **Assign tokens** permission, like “Add token”. That way, neither “Remove” or “Add” would match an existing permission. It doesn’t solve the problem of knowing what a permission does in the UI, but it removes the confusion.

- **2/** Rename “Assign” in the UI to “Mint”, and “Remove” to “Burn”. It would make the relation with the permissions super clear, but these terms might be more difficult to understand by users.

In the long term:

I wonder if it shouldn’t be the role of an app frontend to describe what permissions are being used by it. In this case it is still quite simple, but we can imagine having more complex interfaces in the future, and alternative frontends to a same contract.

Having something like a markdown file with pictures somewhere, describing how the permissions are being used, or more generally how it interacts with the contract, could be super useful. It could be displayed from the app itself (e.g. from the Permissions app), and would contain things like:

> [ screenshot ]
> The “Issue tokens” button shown here requires the **Issue tokens** permission, except if you have checked the “and assign to” checkbox below, in which case it will require the **Mint tokens** permission.

**Comment by sohkai** [comment] 2019-03-22 12:26
> I wonder if it shouldn’t be the role of an app frontend to describe what permissions are being used by it. In this case it is still quite simple, but we can imagine having more complex interfaces in the future, and alternative frontends to a same contract.

Completely agree, we should include more details as part of the `artifact.json`'s schema so we can give more information back to the user: https://github.com/aragon/aragon/issues/486.

**Comment by sohkai** [comment] 2020-03-19 22:53
Closing for https://github.com/aragon/aragon/issues/486 and https://github.com/aragon/aragon/issues/1359; the root problem here is that we do not communicate the mapping between roles and actions effectively.

**Closed by sohkai** 2020-03-19 22:53 UTC
Labels: app: token manager, bug, component: frontend
