### ISSUE TITLE
Voting app shows blank screen

### ISSUE THREAD

**Issue by pythonpete32** [aragon/aragon-apps#994] opened 2019-09-15 13:37 UTC
After the last vote loads the screen goes blank in the voting app.

I've cleared the cache and tried to view it on multiple devices but it get the same thing 

https://rinkeby.aragon.org/#/0xC0d7F939E53de5FE60980cF0357d92230EFB84F3/0x85862138f4f6b22a912e3b3a0c69fd4e887659ff

**Comment by luisivan** [comment] 2019-09-16 10:55
I can reproduce -- some orgs do it, some don't.

Getting this:


```
react-dom.production.min.js:187 TypeError: Cannot read property 'length' of undefined
    at useVotes.js:22
    at Array.map (<anonymous>)
    at useVotes.js:18
    at Object.useMemo (react-dom.production.min.js:160)
    at useMemo (react.production.min.js:23)
    at c (useVotes.js:14)
    at f (useVotes.js:84)
    at P (app-logic.js:77)
    at App.js:21
    at $i (react-dom.production.min.js:148)
Ba @ react-dom.production.min.js:187
n.callback @ react-dom.production.min.js:200
ql @ react-dom.production.min.js:125
$l @ react-dom.production.min.js:125
ru @ react-dom.production.min.js:239
exports.unstable_runWithPriority @ scheduler.production.min.js:20
bl @ react-dom.production.min.js:113
nu @ react-dom.production.min.js:230
Ho @ react-dom.production.min.js:206
(anonymous) @ react-dom.production.min.js:114
exports.unstable_runWithPriority @ scheduler.production.min.js:20
bl @ react-dom.production.min.js:113
xl @ react-dom.production.min.js:114
El @ react-dom.production.min.js:113
Vo @ react-dom.production.min.js:204
la @ react-dom.production.min.js:156
(anonymous) @ index.js:135
s.__tryOrUnsub @ Subscriber.js:192
s.next @ Subscriber.js:130
e._next @ Subscriber.js:76
e.next @ Subscriber.js:53
e._next @ map.js:41
e.next @ Subscriber.js:53
e._next @ map.js:41
e.next @ Subscriber.js:53
r.nextOrComplete @ takeWhile.js:46
r._next @ takeWhile.js:41
e.next @ Subscriber.js:53
e._next @ filter.js:38
e.next @ Subscriber.js:53
e._next @ filter.js:38
e.next @ Subscriber.js:53
s.next @ Subject.js:47
e._next @ Subscriber.js:76
e.next @ Subscriber.js:53
e._next @ map.js:41
e.next @ Subscriber.js:53
e._next @ filter.js:38
e.next @ Subscriber.js:53
(anonymous) @ fromEvent.js:21
Show 10 more frames
useVotes.js:22 Uncaught TypeError: Cannot read property 'length' of undefined
    at useVotes.js:22
    at Array.map (<anonymous>)
    at useVotes.js:18
    at Object.useMemo (react-dom.production.min.js:160)
    at useMemo (react.production.min.js:23)
    at c (useVotes.js:14)
    at f (useVotes.js:84)
    at P (app-logic.js:77)
    at App.js:21
    at $i (react-dom.production.min.js:148)
```

**Comment by izqui** [comment] 2019-09-16 11:32
I am seeing a different error:

```
Uncaught TypeError: s.icon is not a function
```

From some light debugging, it seems that this is happening when reducing vote #13 which performs a Kernel call. On mainnet orgs, Kernel calls seem to be fine (see governance org).

**Comment by luisivan** [comment] 2019-09-16 11:35
I'm getting that error on mainnet orgs as well

**Comment by bpierre** [comment] 2019-09-16 11:37
> I am seeing a different error:
> 
> ```
> Uncaught TypeError: s.icon is not a function
> ```
> 
> From some light debugging, it seems that this is happening when reducing vote #13 which performs a Kernel call. On mainnet orgs, Kernel calls seem to be fine (see governance org).

This seems to be coming from https://github.com/aragon/aragon.js/pull/380/files#diff-9007ed863cba4431686946c9026c1b9aR43 not being there for some reason?

**Comment by bpierre** [comment] 2019-09-16 11:47
We could try [to update it](https://github.com/aragon/aragon-apps/blob/master/apps/voting/app/package.json#L8) to the latest versions of api / api-react, but it should be [in this version](https://github.com/aragon/aragon.js/blob/api-v2.0.0-beta.6/packages/aragon-api/src/index.js#L43) already. Checking the build file to see if it’s actually in there.

**Comment by izqui** [comment] 2019-09-16 11:52
I am pretty sure it's there, since it is loading the icons for votes 1-12, it only crashes when it gets to 13. It must be an aragon.js issue, and it fails when asking for an icon of an app that we don't have.

**Comment by izqui** [comment] 2019-09-16 11:53
> I'm getting that error on mainnet orgs as well

@luisivan Do you have a mainnet org in which this is failing?

**Comment by luisivan** [comment] 2019-09-16 12:06
https://mainnet.aragon.org/#/holdings/0x0953f69d48cc324186f2910c399336aeab2881af

**Comment by bpierre** [comment] 2019-09-17 11:48
@luisivan Do you get the error consistently? What browser are you using? I can’t reproduce it here (Firefox).

**Comment by pythonpete32** [comment] 2019-09-20 07:29
The 0.8.1 update has fixed this

**Comment by bpierre** [comment] 2019-09-20 07:33
Thanks for confirming, closing then!

**Closed by bpierre** 2019-09-20 07:33 UTC
