### ISSUE TITLE
Use entity component and identify when an app creates a vote

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-apps#674] opened 2019-02-14 12:25 UTC
Right now I'm seeing this when I use the Token Manager to create a vote. Will this be automatically fixed when the entity component recognizes apps? If that's the case, feel free to close this off

![image](https://user-images.githubusercontent.com/718208/52786714-e560e300-305b-11e9-8688-64b617e76113.png)

**Comment by sohkai** [comment] 2019-02-14 19:00
Duplicate of #510.

**Closed by sohkai** 2019-02-14 19:00 UTC
Labels: enhancement
